name: Build and deploy CAST web-app

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Debug workspace
        run: |
          echo "Workflow file in use:" $(basename $GITHUB_WORKFLOW)
          echo
          echo "Repo root contents:"
          ls -1
          echo
          echo "Lockfile exists at:"
          ls -l package-lock.json || echo "  → not here"
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "package-lock.json"    # ← exactly here
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Prepare artifact for deployment
        # Vite (or your build) spits out `dist/` in repo root now
        run: mv dist public

      - name: Upload artifact for WordPress.com
        uses: actions/upload-artifact@v4
        with:
          name: wpcom
          path: public
          retention-days: 1
